### ISSUE TITLE
Default to not passing optional arguments when specifying None type

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#113]
@SpheMakh Stimela should default to not  passing optional arguments set to None.

**Comment by SpheMakh** [comment]
I think this is already the case. Do you have an example where its not?

**Comment by bennahugo** [comment]
Already fixed it with a "dismissable" type wrapper. I will push up the fix if I can find it... ray is a mess after all the AR2 work :)

**Comment by SpheMakh** [comment]
Fixed in #146
