### ISSUE TITLE
mode rflag missing in flagdata

### ISSUE THREAD

**Issue by radiosky-abhik** [SpheMakh/Stimela#119]
Can you please add rflag mode in CASA flagdata? Thanks.

**Comment by radiosky-abhik** [comment]
For reference please look into here : https://casa.nrao.edu/docs/taskref/flagdata-task.html

**Comment by radiosky-abhik** [comment]
recipe.add('cab/casa_flagdata', 'threshold_flagging_timefreq',
           {
               "msname"           :   msname,
               "mode"             :   'rflag',
               "correlation"      :   'RR,LL',
               "spw"              :   '',
               "datacolumn"       :  'corrected',
               "timedevscale"     :   10,
               "freqdevscale"     :   10,
               "action"           :   'apply'
           },
    input = INPUT,
    output = OUTPUT,
    label = 'threshold_flagging_timefreq:: Flagging above a local rms')

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by SpheMakh** [comment]
Fixed in 927634b83fd03a52b16690ace72a98e09aa4f019
