### ISSUE TITLE
casa flagdata tfcrop & rflag choices

### ISSUE THREAD

**Issue by radiosky-abhik** [SpheMakh/Stimela#125]
Hi,
    It seems tfcrop options are not included in stimela. Can you please include them. Thanks.

Cheers,
 Abhik

PS. Also similar for rflag options.

When I run the following cab it complains "stimela.recipe.PipelineException: Exception occurred while running pipeline component 'flag_tfcrop:: Flag based on median filtering': Parameter timedevscale is unknown."

# Use tfccrop to median flag
    
    recipe.add("cab/casa_flagdata", "flag_tfcrop",
           {
            "msname"    :   msname,
            "mode"      :   "tfcrop",
            #"combinescans" : True,
            "antenna"       : '81&105;105&97;65&54;54&32;32&66;89&10;10&21;21&90;90&44;106&23;23&82;82&11;73&113;113&98',
            "timedevscale" : '10',
            "freqdevscale" :  '5',
            "datacolumn" : 'DATA',   
           },
    input=INPUT, output=OUTPUT,
    label="flag_tfcrop:: Flag based on median filtering")

**Comment by SpheMakh** [comment]
Fixed in 927634b83fd03a52b16690ace72a98e09aa4f019
