### ISSUE TITLE
CASA startup time

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#129]
Getting very annoying for large number of CASA tasks. I hypothesize that most of the problem comes in when it does initialization of configuration.  It may be worth running casa once during building imaging building. Will try at some point

**Comment by bennahugo** [comment]
So investigated this a bit it is user specific so can't be executed during image build. The alternative is to string casa commands together into a pipeline and fire them off simultaniously

**Comment by bennahugo** [comment]
maybe mount output into home?

**Comment by SpheMakh** [comment]
We could bundle consecutive CASA tasks into a single CASA call. Anything beyond that will be clunky, and probably not worth it.
