### ISSUE TITLE
rflag option in casa's flagdata task

### ISSUE THREAD

**Issue by radiosky-abhik** [SpheMakh/Stimela#135]
Hi Sphe,
              It seems rflag option still does not find all the option in casa flagdata ? This time it did not find 'freqdevscale' option?

///////////////////////////////////////////////////////////////////

recipe.add('cab/casa_flagdata', 'threshold_flagging_timefreq', 
           {
               "msname"           :   msname, 
               "mode"             :   'rflag',    
               "correlation"      :   'RR,LL',
               "spw"              :   '',    
               "datacolumn"       :  'corrected',   
               "timedevscale"     :   10, 
               "freqdevscale"     :   5,  
               "combinescans"     :   True,
               "action"           :   'apply'      
           },
    input = INPUT,
    output = OUTPUT,
    label = 'threshold_flagging_timefreq:: Flagging above a local rms')

**Comment by SpheMakh** [comment]
Its there in master. Please update (git pull), re-install (pip install ....) then re-build stimela
https://github.com/SpheMakh/Stimela/blob/master/stimela/cargo/cab/casa_flagdata/parameters.json#L462

**Comment by SpheMakh** [comment]
Do you still have this issue?

**Comment by radiosky-abhik** [comment]
No. Thanks Sphe.
