### ISSUE TITLE
Missing weighting options in CASA clean definition

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#136]
Seems casa clean is the only imager out there that can do multi-ms radial weighted images sighs... anyways the cab definition is missing ’superuniform’,’briggsabs’,’radial’ for weighting options. Easy enough to fix, will do in the morning.

**Comment by SpheMakh** [comment]
Fixed in https://github.com/SpheMakh/Stimela/commit/47638adc13935bd0de75953a52ac7069dca0ba43
