### ISSUE TITLE
Failures on master

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#145]
@SpheMakh GitHub pull request #139 of commit 16e6a0e1653639348b123cb0d3410871411f6a2f, no merge conflicts is the last PR that ran successfully. I think changing to kern 2 introduced the casacore bug that is giving us these issues. See build #17

**Comment by bennahugo** [comment]
Also not sure why the error status is not being checked.

**Comment by bennahugo** [comment]
I'm running a cron job now. Lets see if the new images fixes the issue

**Comment by SpheMakh** [comment]
Yeah, I was ignoring the container exit status because changes I had made earlier. This will be fixes in a PR I'm about to make

**Comment by SpheMakh** [comment]
see #146

**Comment by SpheMakh** [comment]
Fixed in #146
