### ISSUE TITLE
channel selection in calibrator

### ISSUE THREAD

**Issue by TariqBlecher** [SpheMakh/Stimela#163]
Not essential because one could go through a tdlconfig but would be a commonly used feature to be able to set a channel range directly in the dictionary input for cabs/calibrator.

**Comment by TariqBlecher** [comment]
Oh there's also a typo in the cabs/calibrator parameter "Gjones-smooothing-intervals"

**Comment by SpheMakh** [comment]
Channels can be  selected via a TaQL string using the 'data-selection' option in calibrator

**Comment by SpheMakh** [comment]
Reopen, channel selection not possible on an MS with TaQL.
