### ISSUE TITLE
Is the differential gain calibration enable by default in stimela calibrator?

### ISSUE THREAD

**Issue by kelahard** [SpheMakh/Stimela#167]
Is the differential gain calibration enable by default in the **_calibrator_** (in _stimela_)?
I have looked through the log file but did not see where it is enabled but the plot of the gain solutions for a single source sky model simulation that I did looks like it's enable.

![image](https://user-images.githubusercontent.com/10513679/29127219-c8bdf610-7d20-11e7-8489-dda4e2987235.png)

**Comment by SpheMakh** [comment]
No, you have to set 'DDjones' to True. See the help
```
stimela cabs -i calibrator
```

**Comment by SpheMakh** [comment]
why do you say that this plot suggests that they are enabled?

**Comment by o-smirnov** [comment]
That was my suggestion. The G solutions are going crazy in the one-source case (see plot -- amplitudes well above unity), but only in the one-source case. I was making theories about what could cause this, and one was that if DD gains were inadvertently enabled, then the degeneracy between the G and dE solutions could potentially cause this.

If they're not enabled, then it's back to the drawing board -- what is going on with those solutions? It's a one-source sim, calibrated with the same one-source model, same beam. G should come out unity. WTF? @kelahard over to you, somebody needs to figure this out.

**Comment by SpheMakh** [comment]
Yep, this is very strange indeed. I'll try out a similar simulation, and see what I get.

**Comment by SpheMakh** [comment]
Is @KshitijT getting similar behaviour from his simulations?

**Comment by o-smirnov** [comment]
Dunno, has @KshitijT even tried a one-source case? I emphasize that this **only** happens in the one-source scenario -- in all @kelahard's other sims, the Gs come out near unity.

**Comment by kelahard** [comment]
@SpheMakh below is my script (to help with investigation):
```
import stimela

INPUT = 'input_dir'
OUTPUT = 'output-withcal'
MSDIR = 'msdir'

sky = 16
nchans = 64
direction = "'J2000,85.6500E+00deg,49.8517E+00deg'"

MS = 'beamrot_%s_7.ms'%sky

skymodel = 'skymodel%s-7.txt'%sky    
beam = 'fits/scaled_to_avg_JVLA-L_interp_by_wt_ant5-$(xy)_$(reim).fits'
ripplebeam = 'fits/scaled_JVLA-L_interp_by_wt_ant5-$(xy)_$(reim).fits'

OUTPUT = 'output_beamrot%s_7'%sky  

recipe = stimela.Recipe('Beam rotation test', ms_dir=MSDIR)

recipe.add('cab/simms', 'simms', {
    "msname"    : MS, 
    "synthesis" : 4,
    "dtime"     : 60, 
    "freq0"     : '1.4GHz',
    "dfreq"     : '4MHz',
    "nchan"     : nchans, 
    "direction" : direction, 
    "telescope" : 'vla',
    "feed"      : 'perfect R L',
    "pol"       : 'RR RL LR LL',
},
    input=INPUT,
    output=OUTPUT,
    label='simms:: Make empty MS')


recipe.add('cab/simulator', 'simsky', {
    "msname"    : MS, 
    "skymodel"  : skymodel,
    "addnoise"  : True,
    "sefd"      : 300,
    "threads"   : 16, 
    "column"    : 'DATA',
    "Ejones"    : True,
    "beam-files-pattern"    :ripplebeam,
    "beam-l-axis"   :   'X',
    "beam-m-axis"   :   'Y',
    "parallactic-angle-rotation":  True,
},
    input=INPUT,
    output=OUTPUT,
    label='simsky:: Simulate sky')

recipe.add('cab/wsclean', 'image', {
    "msname"    : MS, 
    "prefix"    : MS[4:-3]+'-sim',
    "column"    : "DATA",
    "weight"    : "briggs -2",
    "cellsize"  : 2, 
    "npix"      : 5120, 
    #"trim"      : 4096,
    "mgain"     : 0.90,
    "niter"     : 5000, 
    "auto-threshold"    : 1,
    "auto-mask" : 3,
},
    input=INPUT,
    output=OUTPUT,
    label='image1:: Image data')

recipe.add('cab/calibrator', 'calibrate', {
    "msname"    : MS,
    "skymodel"  : skymodel,
    "Gjones"    : True,
    "Gjones-solution-intervals" : [1,1],
    "Ejones"    : True,
    "beam-files-pattern" : ripplebeam, 
    "beam-l-axis" : 'X',
    "beam-m-axis" : 'Y',
    "parallactic-angle-rotation":  True,
    "make-plots": True,
    "tile-size" : 512
},
    input=INPUT,
    #output=OUTPUT,
    output=OUTPUT +'/ripple',
    label='calibrate:: Calibrate data1')

recipe.add('cab/wsclean', 'image', {
    "msname"    : MS,
    "prefix"    : MS[4:-3]+'-ripple',
    "column"    : "CORRECTED_DATA",
    "weight"    : "briggs -2",
    "cellsize"  : 2,
    "npix"      : 5120, 
    #"trim"      : 4096,
    "mgain"     : 0.90,
    "niter"     : 5000, 
    "auto-threshold"    : 1,
    "auto-mask" : 3,
},
    input=INPUT,
    #output=OUTPUT,
    output=OUTPUT +'/ripple',
    label='image2:: Image data')

recipe.add('cab/calibrator', 'calibrate2', {
    "msname"    : MS,
    "skymodel"  : skymodel,
    "Gjones"    : True,
    "Gjones-solution-intervals" : [1,1],
    "Ejones"    : True,
    "beam-files-pattern" : beam, 
    "beam-l-axis" : 'X',
    "beam-m-axis" : 'Y',
    "parallactic-angle-rotation":  True,
    "make-plots": True,
    "tile-size" : 512
},
    input=INPUT,
    #output=OUTPUT,
    output=OUTPUT +'/smooth',
    label='calibrate2:: Calibrate data')

recipe.add('cab/wsclean', 'image', {
    "msname"    : MS,
    "prefix"    : MS[4:-3]+'-smooth',
    "column"    : "CORRECTED_DATA",
    "weight"    : "briggs -2",
    "cellsize"  : 2, 
    "npix"      : 5120, 
    #"trim"      : 4096,
    "mgain"     : 0.90,
    "niter"     : 5000, 
    "auto-threshold"    : 1,
    "auto-mask" : 3,
},
    input=INPUT,
    #output=OUTPUT,
    output=OUTPUT +'/smooth',
    label='image3:: Image data')

recipe.run([
    'simms',
    'simsky',
    'image1',
    'calibrate',
    'image2',
    'calibrate2',
    'image3'
], resume=False)

```

My sky model is this:
```
#format: name ra_d dec_d i
s41 86.73777343 49.13485066 2
```

**Comment by KshitijT** [comment]
@o-smirnov , no, I have only come as low as 2 source case, in which I don't see the plots @kelahard has got above. I am trying out the one-source case now. Would not the logs for the calibrator cab show if ddjones was enabled?

**Comment by SpheMakh** [comment]
![stripes](https://user-images.githubusercontent.com/6624280/29132071-3ffe42f8-7d2f-11e7-8a82-edb55a2f2f2a.png)

This explains the stripes in the images @kelahard showed earlier. From the gain amplitude y-range in the plot, there must be a very bad gain point causing the stripes. Clipping gains on amplitude will fix this. 

These are the related options:

```
  Name         Gjones-ampl-clipping
  Description  Gjones amplitude clipping
  Type         bool
  Default      False
 
  Name         Gjones-chisq-clipping
  Description  Gjones chi square clipping
  Type         bool
  Default      False
 
  Name         Gjones-thresh-sigma
  Description  Gjones threshold level
  Type         float
  Default      10
 
  Name         Gjones-ampl-clipping-low
  Description  Gjones flagging amplitude
  Type         float
  Default      0.2
 
  Name         Gjones-ampl-clipping-high
  Description  Gjones flagging amplitude
  Type         float
  Default      1.8

```

**Comment by o-smirnov** [comment]
Well yes, there's definitely one bad gain point causing the stripes -- but even more puzzlingly, the gain amplitudes start to climb from channel 20 onwards...

**Comment by SpheMakh** [comment]
Could it be that the source falls into a null at channel 20?

**Comment by KshitijT** [comment]
I tried out Kela's simulation, and I seem to be getting unusual results as well: 
![image](https://user-images.githubusercontent.com/9251962/29133476-e4c1952a-7d33-11e7-86cd-a65d9b01f2be.png)

**Comment by o-smirnov** [comment]
The null was my first theory... but moving it around didn't help. Actually, @kelahard, do check where the primary beam nulls are at each frequency, would you?

**Comment by SpheMakh** [comment]
I get something more normal. But I'm not using @kelahard's beams
![gains-chans](https://user-images.githubusercontent.com/6624280/29134178-28a0a6b2-7d36-11e7-9a59-c3f115087ee0.png)

**Comment by SpheMakh** [comment]
But the calibration does not converge when the source is at  RA=5:40:33.62  DEC=49:11:03.45

**Comment by KshitijT** [comment]
@SpheMakh , is that for your simulation ? I saw that it does not converge for @kelahard's simulation.

**Comment by SpheMakh** [comment]
![bg_chan](https://user-images.githubusercontent.com/6624280/29136559-eceb73ba-7d3d-11e7-8974-ce3dab75980b.png)

The beam gain for the two source locations, convergence (yes), and non-convergence(no). Its not obvious from this why one case converges and the other doesn't. @kelahard can you show the beam gain using your beams

```
import numpy
import pylab
import astropy.io.fits as fitsio
from astLib.astWCS import WCS

power_beam = 'power_beam.fits'
wcs = WCS(power_beam)
data = fitsio.open('power_beam.fits')[0].data

ra0,dec0 = 85.6505746518512, 49.8520093217819 # Centre coords to get beam and model on same frame
src1_ra, src1_dec = 86.73777343 - ra0,49.13485066 - dec0
src2_ra, src2_dec = 85.140083333333337 - ra0,49.184291666666667 - dec0

raPix1, decPix1 = map(int, wcs.wcs2pix(src1_ra, src2_dec))
raPix2, decPix2 = map(int, wcs.wcs2pix(src2_ra, src2_dec))

line1 = data[:,decPix1,raPix1]
line2 = data[:,decPix2,raPix2]

pylab.plot(line1, label='yes')
pylab.plot(line2, label='no')
pylab.legend()
pylab.savefig('bg_chan.png')
```

**Comment by SpheMakh** [comment]
@KshitijT the only difference seems to be the beams.

**Comment by KshitijT** [comment]
Indeed. I tried out Kela's simulations, this time shifting the source close to the phase centre:
```
#format: name ra_d dec_d i
s41 85.67 49.83 2
```
and I get the following gains, which look more or less ok:

![image](https://user-images.githubusercontent.com/9251962/29137640-4fa06f9e-7d41-11e7-9cd0-c97eb0090997.png)

**Comment by kelahard** [comment]
Below is the plot of the beam gain using the ripple beams.

![image](https://user-images.githubusercontent.com/10513679/29137656-5c2626b4-7d41-11e7-9ac0-27b9ea7d5ace.png)

**Comment by KshitijT** [comment]
@kelahard , is the above plot for the complete L-band? Where does the bandwidth used in the simulation fall ?

**Comment by kelahard** [comment]
@KshitijT the above beam gain plots is for L-band RR - ripple beams using the same script that @SpheMakh  posted.

**Comment by o-smirnov** [comment]
Yes, but the question is, the frequency range of your simulations corresponds to which chunk of the X axis? Your simulation is surely not 1-2 GHz.

**Comment by SpheMakh** [comment]
I've shaded the frequency the simulated range. But this is like the inverse of what I was expecting, since the 'yes' falls into a null. Maybe I mislabelled things
![bg_chan](https://user-images.githubusercontent.com/6624280/29138733-e37c31a0-7d44-11e7-82ae-eab6a92476d8.png)

**Comment by kelahard** [comment]
Repeating the same plot above for channels 392 - 455 (1.4 - 1.463 GHz).

![image](https://user-images.githubusercontent.com/10513679/29138928-68e3ea68-7d45-11e7-8a5f-7053da2575b0.png)

**Comment by KshitijT** [comment]
@kelahard, your channels are 4 MHz? So this should show about 250 MHz bandwidth, right?

**Comment by kelahard** [comment]
Yes @KshitijT. Your are right. Below is the updated plots for channels 392 - 643 (1.4 - 1.652 GHz).

![image](https://user-images.githubusercontent.com/10513679/29140431-b41a5f9e-7d4a-11e7-99e0-9d35709bedc3.png)

**Comment by SpheMakh** [comment]
Ok, I did not mislabel the plots. But there are no gains for the case that doesn't converge, however, the source is subtracted equally well in both cases.

**Comment by SpheMakh** [comment]
I suppose there is the PA rotation which will not be evident in these gain plots. @kelahard maybe move the source into the main lobe.

**Comment by kelahard** [comment]
@SpheMakh if you check CASE 1([Issue 20](https://github.com/ratt-ru/beam-me-up/issues/20)): figure 3 and 4, you will see another case of a single source sky model simulation that is at about 0.75 degree from the center but its gain plot is well behaved. 

I have presented below the beam gain plots for Source 11 (S11) and source 41 (S41). S11 have a well behaved gain solution plots while S41 does not.

![image](https://user-images.githubusercontent.com/10513679/29143454-8924325a-7d55-11e7-96e8-79ca2b608fce.png)

**Comment by kelahard** [comment]
Simulate a sky model with a single source (S30) within the main lobe. Below are the gain solution plots:

|Plots of the gain solutions for calibration done with:| 
| :-------------------------------------------------------------: |

|ripple beams| smooth beams|
| :-------------: | :----------------: | 
![image](https://user-images.githubusercontent.com/10513679/29145581-fa52f7f6-7d5d-11e7-986b-891aecafc672.png) | ![image](https://user-images.githubusercontent.com/10513679/29145655-4e64f7e0-7d5e-11e7-91e6-d1c1a8818fc0.png)

Below are the beam gain plots for Source 11 (S11), source 41 (S41) and  source 30 (S30).

![image](https://user-images.githubusercontent.com/10513679/29145958-713ad5d6-7d5f-11e7-95b2-fcb00092eaf7.png)

**Comment by KshitijT** [comment]
@kelahard , is the beamgain too low within the main lobe - maybe I misunderstood the plot? Could you confirm the position of the source?

**Comment by kelahard** [comment]
@KshitijT here is the imaged simulated visibility. S30 is at  85.9245666, 49.49525997 (RA, DEC). The main lobe of the beams from 1.4 - 1.652 GHz is having a radius of about 0.4 degree.

![image](https://user-images.githubusercontent.com/10513679/29146365-1930beda-7d61-11e7-8080-0554833a29ba.png)

**Comment by SpheMakh** [comment]
@kelahard you should use the power beam for the plots, not RR. 

power beam = (xx_re^2 + xy_re^2 + yx_re^2 + yy_re^2 + xx_im^2 + xy_im^2 + yx_im^2 + yy_im^2)/2
