### ISSUE TITLE
 wsclean 0.3.1 error

### ISSUE THREAD

**Issue by TariqBlecher** [SpheMakh/Stimela#183]
So I built the latest wsclean image as it seems like it was updated to 2.4, however when running a test I get a very general error of :

> running: docker start -a target_image-140653483064224150426165959
> Illegal instruction (core dumped)
> running: /usr/bin/wsclean -name /home/blecher/output/wsclean_target -mem 100 -verbose -weight uniform -superweight 1.0 -weighting-rank-filter-size 16 -size 5000 5000 -trim 4096 4096 -scale 0.64asec -channelsout 1 -gridmode kb -gkernelsize 7 -oversampling 63 -pol I -intervalsout 1 -channelrange 6 122 -datacolumn DATA -niter 1000000 -auto-threshold 0.5 -auto-mask 5 -gain 0.1 -mgain 0.85 -multiscale-scale-bias 0.6 -fitbeam -ellipticalbeam /home/blecher/msdir/30_066-5MAY-AO-4xf-2xt-split.ms
> Traceback (most recent call last):
>   File "/code/run.py", line 54, in <module>
>     utils.xrun(cab['binary'], args + [mslist])
>   File "/utils/utils/__init__.py", line 72, in xrun
>     raise SystemError('%s: returns errr code %d'%(command, process.returncode))
> SystemError: /usr/bin/wsclean: returns errr code 132
> 2017-09-01 12:27:41,955 - STIMELA - INFO - Recipe execution failed while running job target_image
> INFO:STIMELA:Recipe execution failed while running job target_image

This is essentially the same set of parameters which I used for an earlier run on WSCLEAN 2.3 / Stimela 0.3.1 which worked

> running: /usr/bin/wsclean -name /home/blecher/output/wscleancal -mem 100 -weight uniform -superweight 1.0 -weighting-rank-filter-size 16 -size 256 256 -scale 0.5asec -channelsout 1 -gridmode kb -gkernelsi
> ze 7 -oversampling 63 -pol I -intervalsout 1 -channelrange 6 122 -field 1 -datacolumn CORRECTED_DATA -niter 1000000 -auto-threshold 0.5 -auto-mask 5 -gain 0.1 -mgain 0.9 -multiscale-scale-bias 0.6 -fitbea
> m -ellipticalbeam /home/blecher/msdir/30_066-5MAY-AO-4xf-2xt-split.ms

Is it possible to get more diagnostics as to the actual parameter which is failing to be parsed?

**Comment by SpheMakh** [comment]
Could you post the full log file

**Comment by SpheMakh** [comment]
Its should be in the output folder of your pipeline

**Comment by TariqBlecher** [comment]
It's essentially the same as what I posted above

> Stimela version     : 0.3.0
> Cab name            : blecher_cab/wsclean
> -------------------------------------
> Illegal instruction (core dumped)
> running: /usr/bin/wsclean -name /home/blecher/output/wsclean_target -mem 100 -weight uniform -superweight 1.0 -weighting-rank-filter-size 16 -size 5000 5000 -trim 4096 4096 -scale 0.64asec -channelsout 1 
> -gridmode kb -gkernelsize 7 -oversampling 63 -pol I -intervalsout 1 -channelrange 6 122 -datacolumn DATA -niter 1000000 -auto-threshold 0.5 -auto-mask 5 -gain 0.1 -mgain 0.85 -multiscale-scale-bias 0.6 -f
> itbeam -ellipticalbeam /home/blecher/msdir/30_066-5MAY-AO-4xf-2xt-split.ms
> Traceback (most recent call last):
>   File "/code/run.py", line 54, in <module>
>     utils.xrun(cab['binary'], args + [mslist])
>   File "/utils/utils/__init__.py", line 72, in xrun
>     raise SystemError('%s: returns errr code %d'%(command, process.returncode))
> SystemError: /usr/bin/wsclean: returns errr code 132

**Comment by SpheMakh** [comment]
There isn't enough information here. Could you post the options you are parsing to the wsclean cab in your pipeline. I'll try to reproduce this

**Comment by TariqBlecher** [comment]
So you can check out the directory
/home/blecher/phd/systematic/wsclean_test

wsclean_params = {
   "msname": MSlist,
   "name": image_name,
   "npix": 5000,
   "trim": 4096,
   "cleanborder": 0,
   "cellsize":  "0.64asec",
   "column": 'DATA',
   "clean_iterations":  1000000,
   "auto-mask": 5,
   "auto-threshold": 0.5,
   "mgain": 0.85,
   "weight": "uniform"
}
