### ISSUE TITLE
master broken

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#210]
@paoloserra got this issue when installing stimela

```
cp: cannot stat
'/home/pserra/Astro/meerkathi-venv/local/lib/python2.7/site-packages/stimela/cargo/cab/politsiyakat/*':
No such file or directory
Traceback (most recent call last):
  File "/home/pserra/Astro/meerkathi-venv/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File
"/home/pserra/Astro/meerkathi-venv/local/lib/python2.7/site-packages/stimela/__init__.py",
line 608, in main
    _cmd(argv)
  File
"/home/pserra/Astro/meerkathi-venv/local/lib/python2.7/site-packages/stimela/__init__.py",
line 162, in build
    build_args=build_args, args=no_cache)
  File
"/home/pserra/Astro/meerkathi-venv/local/lib/python2.7/site-packages/stimela/docker.py",
line 26, in build
    with open("{}/Dockerfile".format(bdir)) as std:
IOError: [Errno 2] No such file or directory: '/tmp/tmpvRv2wg/Dockerfile'
```

**Comment by SpheMakh** [comment]
I think this is due to a merge conflict which retained parts of politsiyakat after it was removed. The solution for now would be to build using
```
$ stimela build --ignore-cabs politsiyakat 
```

**Comment by bennahugo** [comment]
delete stale .stimela folder; pip uninstall stimela; pip install stimela; to make sure all old cab references are removed.

**Comment by SpheMakh** [comment]
This highlights the need to allow critical patches to be merged into master without having the pass the jenkins test. That is, in some special cases an approval from at least one other admin should be enough to merge. 

What do you think @bennahugo @KshitijT

**Comment by bennahugo** [comment]
No I don't think so - this is a user specific issue.

**Comment by bennahugo** [comment]
If you rely on the bleeding edge you should be prepared for burning - the risks of introducing accidental bugs are too great :)

**Comment by SpheMakh** [comment]
> delete stale .stimela folder; pip uninstall stimela; pip install stimela; to make sure all old cab references are removed. 

This also reminds me that we to emphasise the `stimela clean`  command

```
Convience tools for cleaning up after stimela

optional arguments:
  -h, --help            show this help message and exit
  -ai, --all-images     Remove all images pulled/built by stimela. This
                        include CAB images
  -ab, --all-base       Remove all base images
  -ac, --all-cabs       Remove all CAB images
  -aC, --all-containers
                        Stop and/or Remove all stimela containers
  -bl BUILD_LABEL, --build-label BUILD_LABEL
                        Label for cab images. All cab images will be named
                        <CAB_LABEL>_<cab name>. The default is $USER

```

**Comment by bennahugo** [comment]
yea quite important

**Comment by SpheMakh** [comment]
> If you rely on the bleeding edge you should be prepared for burning - the risks of introducing accidental bugs are too great :)

Hehe, sometimes its good to be reminded why we need to eat our vegetables

**Comment by SpheMakh** [comment]
@bennahugo Note that this crash happened on a fresh (new machine) install

**Comment by bennahugo** [comment]
but how... you removed the old politsiyakat cab before merging into master?

**Comment by bennahugo** [comment]
And that test passed - meaning there was a successful install.

**Comment by paoloserra** [comment]
> delete stale .stimela folder; pip uninstall stimela; pip install stimela; to make sure all old cab references are removed.

That worked.

And no, it wasn't a fresh installation. I had already installed, got issues with the new reporting module of MeerKATHI, and tried again from scratch. (Still need to test whether that problem is now gone)

**Comment by bennahugo** [comment]
@paoloserra Koo Beans in a can. Thanks for helping to test.
