### ISSUE TITLE
simms meerkat 64 antenna table out of date

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#218]
@SpheMakh This array layout is very wrong / very out of date.
@mserylak This is going to affect your simulations.

We need to find someone who knows someone with the latest GPS coordinates....

![wrong_meerkat_anttable](https://user-images.githubusercontent.com/7934586/33143588-01578ae6-cfc3-11e7-816d-00dc64f3a9ce.png)

**Comment by SpheMakh** [comment]
Ben maybe you could elaborate on this, so we are all on the same page.

**Comment by bennahugo** [comment]
@SpheMakh The antenna names on this layout are very wrong. I don't know if it is just the antenna names or their coordinates as well. Lindsay sent the final layout from the contractors to me - they are already in WGS 84 format, so it should be easy to plug in.

**Comment by bennahugo** [comment]
@SpheMakh can you make a release of simms and build the new version for 0.3.2?
