### ISSUE TITLE
Towards release 1.0.0

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#226]
### TODO

**Cab Definition and Recipe and interface**
- Port cabs to CWL files
- Use udocker for containerisation
- Add option for optimised builds 
  - A Dockerfile with additional compile flags (@bennahugo) 

**Update/Add Cabs** 
- Add Galsim
- Add CASA tclean
- Use CASA tf for FITS image predict
- Update CubiCal
- Update DDFacet
- Update WSClean
- Add KillMS* (depends on whether it can be packaged/containerised)

**Comment by bennahugo** [comment]
* add CASA clearcal - useful to clear setjy out of the way :)

**Comment by bennahugo** [comment]
{already done it on my DDFacet branch. Just need to test things then I'll PR}

**Comment by bennahugo** [comment]
* Bugfixes and hard clips necessary in politsiyakat

**Comment by SpheMakh** [comment]
- Add tool to transfer weights from hdf5file to MS
- Add tool to estimate thermal noise (@bennahugo )
