### ISSUE TITLE
Pipeline restart issue

### ISSUE THREAD

**Issue by KshitijT** [SpheMakh/Stimela#234]
Getting the following error often nowadays:
```
raise DockerError("Container [{}] has not been stopped, cannot remove".format(self.name))
DockerError: Container [listobs_0-139743243485960152032349209] has not been stopped, cannot remove
```
The context is this: I killed a pipeline run, made a few changes and tried to restart it -  which is when I got this error. This requires restarting docker, which is an issue if you don't have the permissions and/or on a shared system.

**Comment by SpheMakh** [comment]
Sadly, This is a Docker issue. Stimela does catch a "KeyboardInterupt" exception and then tries to exit the container gracefully to avoid this. But nothing can be done beyond that
