### ISSUE TITLE
stimella throws an error when pulling sublocker

### ISSUE THREAD

**Issue by mserylak** [SpheMakh/Stimela#236]
Hi,

When pulling images with stimela pull I am getting the following error.

kat@com3 [19 Mar 2018 13:02] ~> stimela pull
running: docker pull stimela/tigger:0.3.1
0.3.1: Pulling from stimela/tigger
Digest: sha256:906931dbdbe0ab1f7b0937cd8fd9870c88d6fef40927c4786f225d6af4efd05f
Status: Image is up to date for stimela/tigger:0.3.1
Image stimela/tigger:0.3.1 has already been logged.
running: docker pull stimela/curl:0.3.1
0.3.1: Pulling from stimela/curl
Digest: sha256:abd3a07ef861b296a5efc436420d7586bb228655b29e768e561b4f156f05509a
Status: Image is up to date for stimela/curl:0.3.1
Image stimela/curl:0.3.1 has already been logged.
running: docker pull stimela/ddfacet:0.3.1
0.3.1: Pulling from stimela/ddfacet
8aec416115fd: Already exists 
695f074e24e3: Already exists 
946d6c48c2a7: Already exists 
bc7277e579f0: Already exists 
2508cbcde94b: Already exists 
c1074d96cfa2: Already exists 
e3f7ddb50356: Already exists 
c81025143764: Already exists 
bd765d002bf1: Already exists 
90ac2c759dc3: Already exists 
e6f36ae684e8: Already exists 
8cfbe2b8c60b: Already exists 
23c2199d7b46: Already exists 
Digest: sha256:e44b258a262bec0536b5cf8547e20e946a44af4a19a3bde279218e8947fd906e
Status: Image is up to date for stimela/ddfacet:0.3.1
Image stimela/ddfacet:0.3.1 has already been logged.
running: docker pull stimela/sofia:0.3.1
0.3.1: Pulling from stimela/sofia
Digest: sha256:d826ed24dc3566a5e870d25a6f03a3674268fb68bd10c9186086e97e454a0dff
Status: Image is up to date for stimela/sofia:0.3.1
Image stimela/sofia:0.3.1 has already been logged.
running: docker pull stimela/meqtrees:0.3.1
0.3.1: Pulling from stimela/meqtrees
Digest: sha256:f26a42a495272c308ac2ff83b12c3fefb9bf3a0389c4f6dd8bdaec74257a581f
Status: Image is up to date for stimela/meqtrees:0.3.1
Image stimela/meqtrees:0.3.1 has already been logged.
running: docker pull stimela/msutils:0.3.1
0.3.1: Pulling from stimela/msutils
Digest: sha256:f12437ef5cecb1a79958439edcb484ad40c41b8268c463944437894813859168
Status: Image is up to date for stimela/msutils:0.3.1
Image stimela/msutils:0.3.1 has already been logged.
running: docker pull stimela/rfimasker:0.3.1
0.3.1: Pulling from stimela/rfimasker
Digest: sha256:663683b7c9aefbc1eea4ca4c184fc26b12423bcceb938cb65a4ca226f51230fb
Status: Image is up to date for stimela/rfimasker:0.3.1
Image stimela/rfimasker:0.3.1 has already been logged.
running: docker pull stimela/wsclean:0.3.1
0.3.1: Pulling from stimela/wsclean
Digest: sha256:0262390366df1151a50baf9c78076679b916c9ed6b7f0a5d28c27bf9622c2211
Status: Image is up to date for stimela/wsclean:0.3.1
Image stimela/wsclean:0.3.1 has already been logged.
running: docker pull stimela/cubical:dev
dev: Pulling from stimela/cubical
Digest: sha256:10c95e6561d9305a12f1451b5a3fe63ddf3da3b8c57fbaa6fcfcdcd0ed2e12f6
Status: Image is up to date for stimela/cubical:dev
Image stimela/cubical:dev has already been logged.
running: docker pull stimela/katdal:dev
dev: Pulling from stimela/katdal
Digest: sha256:9e27875747d956e37c090bc81d8daa41a502d36a955d7470ce992b9146d12907
Status: Image is up to date for stimela/katdal:dev
Image stimela/katdal:dev has already been logged.
running: docker pull stimela/aoflagger:0.3.1
0.3.1: Pulling from stimela/aoflagger
Digest: sha256:404096b457d89cb0bcb438b76edc30e1e289fa33c795362c9558cb860577937a
Status: Image is up to date for stimela/aoflagger:0.3.1
Image stimela/aoflagger:0.3.1 has already been logged.
running: docker pull stimela/sunblocker:0.3.1
Error response from daemon: manifest for stimela/sunblocker:0.3.1 not found
Traceback (most recent call last):
  File "/home/kat/.local/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/home/kat/.local/lib/python2.7/site-packages/stimela/__init__.py", line 608, in main
    _cmd(argv)
  File "/home/kat/.local/lib/python2.7/site-packages/stimela/__init__.py", line 342, in pull
    docker.pull(image)
  File "/home/kat/.local/lib/python2.7/site-packages/stimela/docker.py", line 55, in pull
    utils.xrun("docker pull", [image])
  File "/home/kat/.local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 74, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: docker pull: returns errr code 1

**Comment by bennahugo** [comment]
Confirmed, somehow this got broken in 0.3.1:
```
Status: Image is up to date for stimela/aoflagger:0.3.1
running: docker pull stimela/sunblocker:0.3.1
Error response from daemon: manifest for stimela/sunblocker:0.3.1 not found
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/104/projects/pyenv/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/104/projects/pyenv/local/lib/python2.7/site-packages/stimela/__init__.py", line 608, in main
    _cmd(argv)
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/104/projects/pyenv/local/lib/python2.7/site-packages/stimela/__init__.py", line 342, in pull
    docker.pull(image)
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/104/projects/pyenv/local/lib/python2.7/site-packages/stimela/docker.py", line 55, in pull
    utils.xrun("docker pull", [image])
  File "/var/lib/jenkins/jobs/stimela-cron/workspace/104/projects/pyenv/local/lib/python2.7/site-packages/stimela/utils/__init__.py", line 74, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
```

**Comment by bennahugo** [comment]
@SpheMakh @mserylak Pushing the 0.3.1 image of the last successful build on master. Testing now

**Comment by bennahugo** [comment]
Fixed:
```
hugo@ike:~$ docker push stimela/sunblocker:0.3.1
hugo@ike:~$ docker push stimela/sunblocker:0.3.1
The push refers to a repository [docker.io/stimela/sunblocker]
e358521efcd0: Pushed 
152dc24cf5f7: Pushed 
e7a166e321b3: Pushed 
7869714b7b84: Pushed 
05278c229940: Pushed 
1832d68bdeca: Pushed 
0d987cb2f71a: Mounted from stimela/msutils 
12357c792dd4: Mounted from stimela/msutils 
da90d81a8e6b: Mounted from stimela/msutils 
56ed85de3cf5: Mounted from stimela/wsclean 
e8ab77c0dccf: Mounted from stimela/msutils 
174a611570d4: Mounted from stimela/msutils 
f51f76255b02: Mounted from stimela/msutils 
51db18d04d72: Mounted from stimela/msutils 
f1c896f31e49: Mounted from stimela/msutils 
0f5ff0cf6a1c: Mounted from stimela/wsclean 
0.3.1: digest: sha256:b21d9ed9ddcb9626f3dc5d8a3ea001218422d8bd6938c2cd2098344a9b2ddb13 size: 3666
```
https://jenkins.meqtrees.net/job/stimela-cron/105/console:
```
running: docker pull stimela/aoflagger:0.3.1
0.3.1: Pulling from stimela/aoflagger
Digest: sha256:404096b457d89cb0bcb438b76edc30e1e289fa33c795362c9558cb860577937a
Status: Image is up to date for stimela/aoflagger:0.3.1
running: docker pull stimela/sunblocker:0.3.1
0.3.1: Pulling from stimela/sunblocker
Digest: sha256:b21d9ed9ddcb9626f3dc5d8a3ea001218422d8bd6938c2cd2098344a9b2ddb13
Status: Image is up to date for stimela/sunblocker:0.3.1
running: docker pull stimela/astropy:0.3.1
0.3.1: Pulling from stimela/astropy
....
```
