### ISSUE TITLE
CASA tclean

### ISSUE THREAD

**Issue by Sinenhlanhla** [SpheMakh/Stimela#244]
can you please add tclean to stimela. It is believed to work best for wide bandwidth imaging.

**Comment by Athanaseus** [comment]
deconvolver : 
Name of minor cycle algorithm (hogbom,clark,multiscale,mtmfs,mem,clarkstokes)Each of the following algorithms operate on residual images and psfs from the gridder and produce output model and restored images. Minor cycles stop and a major cycle is triggered when cyclethreshold or cycleniter are reached. For all methods, components are picked from the entire extent of the image or (if specified) within a mask.hogbom : An adapted version of Hogbom Clean [Hogbom, 1974] - Find the location of the peak residual - Add this delta function component to the model image - Subtract a scaled and shifted PSF of the same size as the image from regions of the residual image where the two overlap.

- Repeatclark : An adapted version of Clark Clean [Clark, 1980] - Find the location of max(I+Q+U+V) - Add delta functions to each stokes plane of the model image - Subtract a scaled and shifted PSF within a small patch size from regions of the residual image where the two overlap. - After several iterations trigger a Clark major cycle to subtract components from the visibility domain, but without de-gridding.

 - Repeat( ***Note : ’clark’ maps to imagermode=” in the old clean task. ’clark_exp’ is another implementation that maps to imagermode=’mosaic’ or ’csclean’ in the old clean task but the behavior is not identical. For now, please use deconvolver=’hogbom’ if you encounter problems. )***

clarkstokes : Clark Clean operating separately per Stokes plane(Note : ’clarkstokes_exp’ is an alternate version. See above.)multiscale : MultiScale Clean [Cornwell, 2008] - Smooth the residual image to multiple scale sizes 

- Find the location and scale at which the peak occurs - Add this multiscale component to the model image - Subtract a scaled,smoothed,shifted PSF (within a small patch size per scale) from all residual images - Repeat from step 2mtmfs : Multi-term (Multi Scale) Multi-Frequency Synthesis [Rau and Cornwell, 2011] - Smooth each Taylor residual image to multiple scale sizes 

- Solve a NTxNT system of equations per scale size to compute Taylor coefficients for components at all locations - Compute gradient chi-square and pick the Taylor coefficients and scale size at the location with maximum reduction in chi-square - Add multi-scale components to each Taylor-coefficient model image - Subtract scaled,smoothed,shifted PSF (within a small patch size per scale) from all smoothed Taylor residual images

 - Repeat from step 2mem : Maximum Entropy Method [Cornwell and Evans, 1985] - Iteratively solve for values at all individual pixels via the MEM method. It minimizes an objective function of chi-square plus entropy (here, a measure of difference between the current model and a flat prior model).(Note : This MEM implementation is not very robust. Improvements will be made in the future.)```
```
  |   | allowed: | string
  |   | Default: | hogbom
```
