### ISSUE TITLE
Revert politsiyakat dockerfile to 0.3.1

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#246]
@SpheMakh 
The current dockerfile installs matplotlib, etc from kern3 ubuntu 16.04

There is a bug in newer versions of matplotlib that prevents grid plots from working correctly. The version of matplotlib in politsiyakat is the last version that I know works correctly.

I'm going to revert the dockerfile back and push the image to the current 0.3.2 tag so we can get a working version for the pipeline.

**Comment by SpheMakh** [comment]
Fixed
