### ISSUE TITLE
be more specific which docker tag to use

### ISSUE THREAD

**Issue by gijzelaerr** [SpheMakh/Stimela#26]
Now in various containers you do for example:

```
FROM kernsuite/casa
```

Which would base your image on the `latest` tag. This is bad for reproducibility. The `latest` tag for an image may be updated to an image that is incompatible with your requirements.

**Comment by SpheMakh** [comment]
Fixed in [formalise-cabs](https://github.com/SpheMakh/Stimela/commits/formalise-cabs)
