### ISSUE TITLE
model-list in Cubical

### ISSUE THREAD

**Issue by KshitijT** [SpheMakh/Stimela#279]
I am trying to run Cubical through a Stimela script. I get this error:
```
gocubical: error: no such option: --model-list
```
The model-list parameter is being set in the script as:

```
"model-list" : ['MODEL_DATA']
```
@SpheMakh , any idea as to what I am missing here?

**Comment by SpheMakh** [comment]
are you using the latest master branch?

**Comment by KshitijT** [comment]
Yes.

**Comment by SpheMakh** [comment]
Could you re-pull the image
```
docker pull stimela/cubical:dev
```

Then re-build the cabs
