### ISSUE TITLE
add mvftoms

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#280]
Its in katdal https://github.com/ska-sa/katdal

**Comment by bennahugo** [comment]
This requires you to setup a credentials file in .aws folder. These cannot be shared outside the organization.

**Comment by bennahugo** [comment]
Also you have to install ms and s3 support, both optional - pip install katdal[ms,s3]

**Comment by SpheMakh** [comment]
Lets add an argument to parse the folder as an input `--credentials-dir`
