### ISSUE TITLE
Incorporate kliko 

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#31]
use [kliko](https://github.com/gijzelaerr/kliko) to handle task parameters and container I/O

**Comment by SpheMakh** [comment]
This taking too much effort, and requires fundamental changes to workflow. Its better to formalise the definition of a cab. This is being done on this [branch](https://github.com/SpheMakh/Stimela/tree/formalise-cabs)

**Comment by gijzelaerr** [comment]
jeej to duplicating effort +1
