### ISSUE TITLE
CubiCal Error: 'de-item'

### ISSUE THREAD

**Issue by Sinenhlanhla** [SpheMakh/Stimela#314]
stimela does not allow for the assignment/adjustment of 'de' terms in cubical. I realized that stimela cabs -i cubical has it as 'dd-item' where as the cubical parset file has it as 'de-item'.

This is the error:
gocubical: error: no such option: --dd-freq-int
Traceback (most recent call last):
  File "/scratch/code/run.py", line 40, in <module>
    utils.xrun(cab['binary'], parset+args)
  File "/scratch/stimela/utils/__init__.py", line 73, in xrun
    raise SystemError('%s: returns errr code %d'%(command, process.returncode))
SystemError: gocubical: returns errr code 2

**Comment by SpheMakh** [comment]
The 'dd'/'de' are just labels. But suspect that you did not set 'dd' in the 'sol-jones' options. Could you post your cubical cab options here

**Comment by Sinenhlanhla** [comment]
recipe.add('cab/cubical', 'cub_cal', {
      "data-ms"          : MS_cub,
      "data-column"      : 'DATA',
      "out-model-column" : 'MODEL_DATA',
      "sol-term-iters"   : '50',
      "data-time-chunk"  : 32,
      "data-freq-chunk"  : 32,
      "dist-ncpu"        : 2,
      "sol-jones"        : solution,
      "sol-precision"    : '32',
      "model-list"       : 'J0034sky.lsm.html@dE:output'.format(MS_cub[:-3]),
      "model-ddes"       : 'auto',
      "out-name"         : PREFIX_cub,
      "out-mode"         : 'sr',
      "out-plots"        : True,
      "weight-column"    : 'WEIGHT',
      "montblanc-dtype"  : 'double',
      "montblanc-feed-type"  : 'circular',
      "g-solvable"       : True,
      "g-type"           : 'complex-2x2',
      "g-time-int"       : 16,
      "g-freq-int"       : 8,
      "g-clip-low"       : 0.5,
      "g-clip-high"      : 1.5,
      "g-clip-after"     : 5,
      "g-max-iter"       : 200,
      "g-max-prior-error": 0.1,
      "g-max-post-error" : 0.1,
      },


solution = 'G,dE'

**Comment by SpheMakh** [comment]
set sol-jones to 'dd', then prefix your direction-dependent options with 'dd'
