### ISSUE TITLE
simms creation with problems again

### ISSUE THREAD

**Issue by mserylak** [SpheMakh/Stimela#327]
While running simms in stimela with:

`makems(msname="/home/kat/msdir/0045-7042core18.ms", label="None", tel="meerkat", pos="/input/antenna_config.txt", pos_type="ascii", synthesis=0.004444, scan_length=None, dtime="8.0", freq0=['1379.923828125MHz'], dfreq=['0.208984375MHz'], nchan=[1], stokes="XX XY YX YY", start_time=None, setlimits=False, elevation_limit=0.000000, shadow_limit=0.000000, coords="itrf",lon_lat="None", noup=False, nbands=1, direction=['J2000,00h45m25.6901s,-70d42m07.0992s'], outdir=".",date="UTC,2019/01/01/18:00:00",fromknown=False, feed="perfect X Y",scan_lag=0,auto_corr=False)`

one can see that 

`scan_length=None`

then in casasm.py (created automatically) one gets error:
`  File "/usr/local/lib/python2.7/dist-packages/simms/casasm.py", line 183, in makems`
`    print sum(scan_length)/3600.0`
`TypeError: 'NoneType' object is not iterable`

Which makes the whole skit to return:
`ERROR: simms.py returns errr code 1. Having Trouble accessing the MS. Something went wrong while creating the MS, please check the logs.`
`If you believe this is due to a bug in simms, please notify me via https://github.com/SpheMakh/simms/issues/new`

Seems that this `print` statement is a debug leftover?

**Comment by bennahugo** [comment]
Somebody touched 1.0.0 4 days ago: 
![image](https://user-images.githubusercontent.com/7934586/51396160-36f27c80-1b47-11e9-9655-02a4089a5c61.png)

I will roll back the image to the following 1.0.0:
```
> $ docker image ls | grep simms                                                                                                                                                  [±py3ize ✓]
bhugo_cab/simms                       latest              fde5bc276798        4 days ago          3.42GB
stimela/simms                         1.0.0               e4e547361c98        2 weeks ago         3.42GB
stimela/simms                         <none>              65789f4d0aef        9 months ago        3.41GB
stimela/simms                         0.3.0               076fccc49c60        18 months ago       3.34GB
stimela/simms                         0.2.8               35202920c895        23 months ago       3.34GB
stimela/simms                         latest              53d1471655f1        2 years ago         3.25GB
```
Please do not push images under the 1.0.0 tag!!!

**Comment by bennahugo** [comment]
@mserylak done
