### ISSUE TITLE
Issues with stimela installation in 'aretha'

### ISSUE THREAD

**Issue by radiosky-abhik** [SpheMakh/Stimela#331]
Hi Sphe,
               I am trying to install stimela in a virtual environment in 'aretha', but when Ben & I are trying 'stimela build' it is giving some error. It seems stimela is installed in the root, and Ben is suggesting to remove it if possible. Can you please help.

PS. This is the error:
(venv) abhik@aretha: stimela build
Traceback (most recent call last):
  File "/usr/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/usr/lib/python2.7/dist-packages/stimela/__init__.py", line 522, in main
    _cmd(argv)
  File "/usr/lib/python2.7/dist-packages/stimela/__init__.py", line 134, in build
    build_args=build_args, args=no_cache)
  File "/usr/lib/python2.7/dist-packages/stimela/docker.py", line 23, in build
    stdw = tempfile.NamedTemporaryFile(dir=build_path)
  File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/usr/lib/python2.7/dist-packages/stimela/cargo/cab/casa_uvsub/tmpdJN2gj'

Thanks,
 Abhik

**Comment by SpheMakh** [comment]
I think you have the system stimela in your PYTHONPATH. What do you get when you run `echo $PYTHONPATH `

**Comment by radiosky-abhik** [comment]
abhik@aretha: echo $PYTHONPATH
/home/abhik/.local/lib/python2.7/site-packages:

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by SpheMakh** [comment]
Please unset it 

`export PYTHONPATH="" ` 

Then delete logged stimela info

 `rm - r. $HOME/.stimela`

Then re-build stimela

**Comment by bennahugo** [comment]
Think this is probably not wise to  install a non-dpkg python package directly into the system directories. Python will look there first before considering pythonpath, see
https://docs.python.org/3/tutorial/modules.html#the-module-search-path
e.g.
In [2]: sys.path
Out[2]: 
['',
 '/usr/local/bin',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/local/lib/python2.7/dist-packages/IPython/extensions',
 '/home/bhugo/.ipython']

**Comment by radiosky-abhik** [comment]
Thanks Sphe. Seems like we still get the problem:

(venv) abhik@aretha: stimela build
Traceback (most recent call last):
  File "/usr/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/usr/lib/python2.7/dist-packages/stimela/__init__.py", line 522, in
main
    _cmd(argv)
  File "/usr/lib/python2.7/dist-packages/stimela/__init__.py", line 134, in
build
    build_args=build_args, args=no_cache)
  File "/usr/lib/python2.7/dist-packages/stimela/docker.py", line 23, in
build
    stdw = tempfile.NamedTemporaryFile(dir=build_path)
  File "/usr/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied:
'/usr/lib/python2.7/dist-packages/stimela/cargo/cab/casa_uvsub/tmpUtQOvO'

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by KshitijT** [comment]
@radiosky-abhik , are you on the docker group on Aretha?

**Comment by radiosky-abhik** [comment]
Yes I think

(venv) abhik@aretha: grep /etc/group -e "docker"
docker:x:132:oms,gijs,makhathini,kshitij,abhik,hugo,blecher,iniyan

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by SpheMakh** [comment]
Fixed
