### ISSUE TITLE
something wrong with tests

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#356]
The failure tests keep failing in unpredictable ways. I'm bot sure why this is happening. But I'm commenting removing it till we fix it

**Comment by bennahugo** [comment]
@SpheMakh I would prefer you keep the failure checks in. There is a good reason to have them in the first place - these non-deterministic failures simply highlights there is something wrong with stimela.

**Comment by SpheMakh** [comment]
I'll put them back in as soon as I figure out what's going wrong. The thing is, nothing can go through right now and I have no idea how to fix this at the moment and it's holding up everything.

**Comment by bennahugo** [comment]
Well that just means we have to check the jenkins log for every PR. I would prefer that to removing all the failure checks

**Comment by SpheMakh** [comment]
One thing I'm going to change is the use of a dummy MS. This is not good since nothing but a "corrupt" MS can be tested, e.g., parsing wrong parameter for any other option is useless at the moment

**Comment by bennahugo** [comment]
Of course you can add more tests, but the idea is to let the parameters validate and ensure the software crashes predictably.

**Comment by SpheMakh** [comment]
> Well that just means we have to check the jenkins log for every PR. I would prefer that to removing all the failure checks 

I've been doing this for a week now. Its simply too annoying
