### ISSUE TITLE
update sofia to v1.3.0

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#365]
From @paoloserra 
> @SpheMakh can we add https://github.com/SoFiA-Admin/SoFiA/releases/tag/v1.3.0 to the list? Thanks

**Comment by paoloserra** [comment]
Based on the new SoFiA default config https://github.com/SoFiA-Admin/SoFiA/blob/master/SoFiA_default_input.txt and on https://raw.githubusercontent.com/SpheMakh/Stimela/master/stimela/cargo/cab/sofia/parameters.json these are the SoFiA 1.3.0 parameters that seem to be missing and should be included in Stimela (and their default values):

- pipeline.trackMemory = false
- steps.doFilterArtefacts = false
- import.invertData = false
- import.sources = []
- scaleNoise.gridSpectral = 0
- filterArtefacts.threshold = 4.0
- filterArtefacts.dilation = 3
- merge.maxSizeX = -1
- merge.maxSizeY = -1
- merge.maxSizeZ = -1
- merge.minVoxels = 1
- merge.maxVoxels = -1
- merge.minLoS = 1
- merge.maxLoS = -1
- merge.minFill = -1
- merge.maxFill = 2
- merge.minIntens = -9e+30
- merge.maxIntens = 9e+30
- merge.positivity = false
- parameters.getUncertainties = false
- writeCat.outputDir =

**Comment by paoloserra** [comment]
Note also that the default value of a few old parameters has changed:

- reliability.parSpace = ['snr_mean', 'snr_sum', 'snr_max']
- reliability.fMin = 10.0
- reliability.scaleKernel = 0.5
- reliability.threshold = 0.9
- parameters.dilateMask = false
- parameters.dilateChanMax = 3
