### ISSUE TITLE
Wrong merge.maxVoxels default value for sofia (follow-up on issue #365)

### ISSUE THREAD

**Issue by edeblok** [SpheMakh/Stimela#384]
The value for `merge.maxVoxels` has the wrong value in 
`Stimela/stimela/cargo/cab/sofia/parameters.json`. (line 836)
It is currently "1" and should be "-1".  Incorrect value results in all detected sofia sources being rejected at merge stage (affecting selfcal and wsclean masks in the meerkathi pipeline). Value was listed correctly in request #365 by @paoloserra

**Comment by SpheMakh** [comment]
Noted. Will fix in next release which will be available later today
