### ISSUE TITLE
Log pipeline information. Remember where pipeline last stopped/crashed 

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/Stimela#4]
If running a long job, it would be nice to be able to resume from last step. Technically, this can be done manually by explicitly specifying steps to run in `Pipeliner.run()`.  But it makes sense to pick up the pipeline from where it was stopped (or failed) by default.

**Comment by sjperkins** [comment]
Somewhat implemented by https://github.com/SpheMakh/Stimela/pull/38 and https://github.com/SpheMakh/Stimela/pull/40

**Comment by SpheMakh** [comment]
Fixed in [formalise-cabs](https://github.com/SpheMakh/Stimela/commits/formalise-cabs)
