### ISSUE TITLE
Cubical/out-name is a string not a file

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#415]
```
{
            "info": "Base name of output files.", 
            "dtype": "file", 
            "default": null, 
            "name": "out-name", 
            "io": "output"
}, 
```
change this to a string not a file. output should not be appended to it because the entire directory can be moved by cubical

**Comment by bennahugo** [comment]
As per discussion on https://github.com/ska-sa/meerkathi/issues/511

**Comment by KshitijT** [comment]
Noted.

**Comment by SpheMakh** [comment]
According to the documentation, it can be a prefix that includes a path. 

https://github.com/ratt-ru/CubiCal/blob/master/cubical/DefaultParset.cfg#L44
