### ISSUE TITLE
RuntimeError: Parameter field is required but has not been specified

### ISSUE THREAD

**Issue by HaoChen1987** [SpheMakh/Stimela#460]
The MeerKATHI pipeline crash at the stage of `plot_delay_cal_0` and `plot_bandpass_0`.

I made the following `stimela` recipe to further test the issue.
Issue are got by running with both udocker (python2) and singularity (python3).

```
import os
import stimela

msname = '1547413577.ms'
prefix = '3577-1547413577-1gc1'
step = 'plot_delay_cal_{0:d}'.format(0)
table = prefix+".K0"

recipe = stimela.Recipe('Make Pipeline', ms_dir='msdir',JOB_TYPE='udocker') #,singularity_image_dir=os.environ["SINGULARITY_PULLFOLDER"])

recipe.add('cab/ragavi', step,
                   { 
                     "table": '{0:s}:{1:s}'.format(table, 'output'),
                     "gaintype": "K",
                      "field": 0,
                     "corr": 'XX',
                     "htmlname": 'test.html'
                     },
                     input='input',
                     output='output',
                     label='{0:s}:: Plot gaincal phase ms={1:s}'.format(step, msname))

recipe.run()
```

> 2019-09-10 16:57:13,683 - STIMELA - INFO - ---------------------------------
2019-09-10 16:57:13,684 - STIMELA - INFO - Stimela version 1.2.1
2019-09-10 16:57:13,684 - STIMELA - INFO - Sphesihle Makhathini <sphemakh@gmail.com>
2019-09-10 16:57:13,685 - STIMELA - INFO - Running: Make Pipeline
2019-09-10 16:57:13,685 - STIMELA - INFO - ---------------------------------
2019-09-10 16:57:13,744 - STIMELA - INFO - Adding cab 'stimela/ragavi:1.2.0' to recipe. The container will be named 'plot_delay_cal_0'
INFO:STIMELA:Adding cab 'stimela/ragavi:1.2.0' to recipe. The container will be named 'plot_delay_cal_0'
2019-09-10 16:57:13,745 - STIMELA - INFO - Running job plot_delay_cal_0
INFO:STIMELA:Running job plot_delay_cal_0
2019-09-10 16:57:13,745 - STIMELA - INFO - STEP 1 :: plot_delay_cal_0:: Plot gaincal phase ms=1547413577.ms
INFO:STIMELA:STEP 1 :: plot_delay_cal_0:: Plot gaincal phase ms=1547413577.ms
Traceback (most recent call last):
  File "/idia/projects/vela/meerkathi-venv-python2/local/lib/python2.7/site-packages/stimela/recipe.py", line 1025, in run
    run_job()
  File "/idia/projects/vela/meerkathi-venv-python2/local/lib/python2.7/site-packages/stimela/recipe.py", line 144, in run_udocker_job
    self.job.parameter_file_name)
  File "/idia/projects/vela/meerkathi-venv-python2/local/lib/python2.7/site-packages/stimela/cargo/cab/__init__.py", line 234, in update
    "Parameter {} is required but has not been specified".format(param0.name))
RuntimeError: Parameter field is required but has not been specified
Traceback (most recent call last):
  File "/idia/projects/vela/meerkathi-venv-python2/bin/stimela", line 14, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/idia/projects/vela/meerkathi-venv-python2/local/lib/python2.7/site-packages/stimela/main.py", line 638, in main
    _cmd(argv)
  File "/idia/projects/vela/meerkathi-venv-python2/local/lib/python2.7/site-packages/stimela/main.py", line 260, in run
    exec(stdr.read(), _globals)
  File "<string>", line 23, in <module>
  File "/idia/projects/vela/meerkathi-venv-python2/local/lib/python2.7/site-packages/stimela/recipe.py", line 1059, in run
    "An unhandled exception has occured. This is a bug, please report")
RuntimeError: An unhandled exception has occured. This is a bug, please report

**Comment by KshitijT** [comment]
Field needs to be a list, not an int. :)

**Comment by HaoChen1987** [comment]
The original MeerKATHI error is here:

> meerkathi - 2019-09-09 17:30:06,778 CRITICAL - INFO:STIMELA-5:Stopping container [3e9]. The container ID is printed below.
meerkathi - 2019-09-09 17:30:06,778 INFO - Running: singularity instance.stop 3e9
meerkathi - 2019-09-09 17:30:07,786 INFO - Stopping 3e9 instance of /idia/projects/vela/meerkathi-venv/singularity/stimela_casa_1.2.0.img (PID=3839)
meerkathi - 2019-09-09 17:30:07,786 CRITICAL - INFO:STIMELA-5:Running job plot_delay_cal_0
meerkathi - 2019-09-09 17:30:07,786 CRITICAL - INFO:STIMELA-5:STEP 6 :: plot_delay_cal_0:: Plot gaincal phase ms=1547413577.ms
meerkathi - 2019-09-09 17:30:07,923 CRITICAL - Traceback (most recent call last):
meerkathi - 2019-09-09 17:30:07,924 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 1025, in run
meerkathi - 2019-09-09 17:30:07,924 CRITICAL -     run_job()
meerkathi - 2019-09-09 17:30:07,924 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 133, in run_singularity_job
meerkathi - 2019-09-09 17:30:07,924 CRITICAL -     self.job.parameter_file_name)
meerkathi - 2019-09-09 17:30:07,924 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/cargo/cab/__init__.py", line 234, in update
meerkathi - 2019-09-09 17:30:07,924 CRITICAL -     "Parameter {} is required but has not been specified".format(param0.name))
meerkathi - 2019-09-09 17:30:07,924 CRITICAL - RuntimeError: Parameter field is required but has not been specified
meerkathi - 2019-09-09 17:30:07,924 ERROR - An unhandled exeption occured. If you think this is a bug please report it.
meerkathi - 2019-09-09 17:30:07,924 ERROR - Your logfile is here: /idia/projects/vela/test_Hao/1547413577/log-meerkathi.txt.
meerkathi - 2019-09-09 17:30:07,924 ERROR - You are running version: 0.2.0
meerkathi - 2019-09-09 17:30:07,969 ERROR - Traceback (most recent call last):
  File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 1025, in run
    run_job()
  File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 133, in run_singularity_job
    self.job.parameter_file_name)
  File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/cargo/cab/__init__.py", line 234, in update
    "Parameter {} is required but has not been specified".format(param0.name))
RuntimeError: Parameter field is required but has not been specified

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/meerkathi/main.py", line 159, in __run
    pipeline.run_workers()
  File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/meerkathi/workers/worker_administrator.py", line 249, in run_workers
    recipe.run()
  File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 1059, in run
    "An unhandled exception has occured. This is a bug, please report")
RuntimeError: An unhandled exception has occured. This is a bug, please report

> meerkathi - 2019-09-09 17:30:07,969 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 1025, in run
meerkathi - 2019-09-09 17:30:07,969 CRITICAL -     run_job()
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 133, in run_singularity_job
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -     self.job.parameter_file_name)
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/cargo/cab/__init__.py", line 234, in update
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -     "Parameter {} is required but has not been specified".format(param0.name))
meerkathi - 2019-09-09 17:30:07,970 CRITICAL - RuntimeError: Parameter field is required but has not been specified
meerkathi - 2019-09-09 17:30:07,970 CRITICAL - 
meerkathi - 2019-09-09 17:30:07,970 CRITICAL - During handling of the above exception, another exception occurred:
meerkathi - 2019-09-09 17:30:07,970 CRITICAL - 
meerkathi - 2019-09-09 17:30:07,970 CRITICAL - Traceback (most recent call last):
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/meerkathi/main.py", line 159, in __run
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -     pipeline.run_workers()
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/meerkathi/workers/worker_administrator.py", line 249, in run_workers
meerkathi - 2019-09-09 17:30:07,970 CRITICAL -     recipe.run()
meerkathi - 2019-09-09 17:30:07,971 CRITICAL -   File "/idia/projects/vela/meerkathi-venv/lib/python3.7/site-packages/stimela/recipe.py", line 1059, in run
meerkathi - 2019-09-09 17:30:07,971 CRITICAL -     "An unhandled exception has occured. This is a bug, please report")
meerkathi - 2019-09-09 17:30:07,971 CRITICAL - RuntimeError: An unhandled exception has occured. This is a bug, please report
meerkathi - 2019-09-09 17:30:07,977 INFO - PIPELINER EXITS WITH RETURN CODE 1

**Comment by SpheMakh** [comment]
This is a bug in stimela. The int zero is the same false, so the conditional here
https://github.com/SpheMakh/Stimela/blob/master/stimela/cargo/cab/__init__.py#L232 
is flawed.

**Comment by KshitijT** [comment]
@HaoChen1987 , yes, see issue 592 on meerkathi. If you have installed meerkathi in dev mode, you can do the following in the worker:
```
            if pipeline.enable_task(config['bp_cal'],'plot'):
                step = 'plot_bandpass_{0:d}'.format(i)
                fieldtoplot = []
                fieldtoplot.append(utils.get_field_id(msinfo, field)[0])

```
(the last two lines are additions) and by saying
```
                     "field"        : fieldtoplot,
```

**Comment by SpheMakh** [comment]
@KshitijT that  is a good workaround
