### ISSUE TITLE
drivecasa in Stimela v.1.2.2 and casa v. 5.6.0

### ISSUE THREAD

**Issue by nkululekoq** [SpheMakh/Stimela#468]
I am trying to use cab/casa_plotants in Stimela version 1.2.2 and 1.2.3 and I am getting this error:
2019-09-29 18:15:43,777 - STIMELA - INFO - Starting container [plot_ants-13989080507960015697736162]. Timeout set to -1. The container ID is printed below.
INFO:STIMELA:Starting container [plot_ants-13989080507960015697736162]. Timeout set to -1. The container ID is printed below.
Running: docker start -a plot_ants-13989080507960015697736162
Starting virtual X frame buffer: Xvfb.
Traceback (most recent call last):
  File "/scratch/code/run.py", line 4, in <module>
    import drivecasa
ImportError: No module named drivecasa
Stopping virtual X frame buffer: Xvfb.

This is what I have in my script:
    recipe.add("cab/casa_plotants", "plot_ants",
        {
            "vis"		:   MS,
            "figfile"		:   str(subarray).split()[0]+'-ants_pos.png',
        },
        input=INPUT,
        output=OUTPUT,
        label='plot_ants_pos:: Plot antenna positions')

After doing some digging, I found that this is related to colour code options... https://github.com/timstaley/drive-casa/issues/7. 

Is there a workaround for this or is there something I might have missed during installation?

Thank you.

**Comment by bennahugo** [comment]
This should use stimela 4.7 from 1.0.1  not 5. Casa 5's plotants dont work
without clicking buttons on the gui to dump to png

**Comment by bennahugo** [comment]
I meant casa 4.7

**Comment by nkululekoq** [comment]
Issue resolved.
