### ISSUE TITLE
CASA 4.7 cabs don't work under singularity

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#475]
As per sphe's comment
```
Singularity stimela_casa_0.3.0.img:/home/sphe/work/MISC/test_casa47> echo $HOME
/root

Singularity stimela_casa_1.2.0.img:~/work/MISC/test_casa47> echo $HOME
/home/sphe
```

**Comment by SpheMakh** [comment]
> Why not pass a environment flag into singularity at runtime to set the home to os.environ["HOME"]?

Singularity does take environmental variables, but they can be parsed in the singularity runscript (the cab/singularity_run file) at runtime.
