### ISSUE TITLE
SetJy

### ISSUE THREAD

**Issue by bennahugo** [SpheMakh/Stimela#58]
Okay when I run the stimela/casa container I finally get confirmation that setjy doesn't pick stuff up:
```
2017-01-14 09:26:12     SEVERE  setjy::FluxStandard::compute    0408-65 is not recognized by Perley-Butler 2013
```

Not sure how this one can be fixed then if it doen't pick the stuff up I wrote into the tables. Will probably need to contact NRAO to get a solution @o-smirnov do you have a contact within the NRAO CASA team that we can ping?

**Comment by bennahugo** [comment]
or an easier solution is perhaps to read the information in vermeerkat and use manual standards...

**Comment by o-smirnov** [comment]
You could ping Urvashi.

**Comment by SpheMakh** [comment]
This is not a stimela issue. I'm closing this
