### ISSUE TITLE
casa uvsub

### ISSUE THREAD

**Issue by radiosky-abhik** [SpheMakh/Stimela#65]
Hi Sphe,
               Can you please add UVSUB task of CASA in Stimela? Thanks.

Cheers,
 Abhik

**Comment by SpheMakh** [comment]
Will do. But you could use  `msutils.addcols()` which is actually more general.

For example, to subtract MODEL_DATA from DATA you would add this to your recipe

```
recipe.add('cab/msutils', 'subtract_vis', {
    "command" :  'sumcols'
    "msname"   :   <msname>,
    "col1"   :   'DATA',
    "col2"       :  'MODEL_DATA',
    "outcol"   :  'CORRECTED_DATA',
    "subtract"   :  True,   # will sum the columns if this is False
 },
     input=<input folder>,
     output=<output folder>,
    label='subtract_cols:: Subtract columns')
```

**Comment by radiosky-abhik** [comment]
Thanks Sphe.

Cheers,
 Abhik

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by radiosky-abhik** [comment]
Hi Sphe,
               If you manage to solve the add/subtract column issue in
msutils please let me know. I will give it a try. Thanks.

Cheers,
 Abhik

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by radiosky-abhik** [comment]
Hi Sphe,
               Did you mange to see the add/subtract column issue?
Cheers,
 Abhik

--  Abhik

<abhik@phy.iitkgp.ernet.in>

**Comment by SpheMakh** [comment]
Yep, its there on the latest release. 
```
pip install stimela --user --upgrade
```

**Comment by radiosky-abhik** [comment]
Hi Sphe,
               Do you have some idea how can I easily increase the point
source flux (may be by factor of 100 or so) in nvss1deg.lsm.html? Can it be
done by tigger?

Cheers,
 Abhik

--  Abhik

<abhik@phy.iitkgp.ernet.in>
