### ISSUE TITLE
In Stimela, the plots of the gain solutions has a fixed y-axis limits

### ISSUE THREAD

**Issue by kelahard** [SpheMakh/Stimela#93]
The _gain solutions_ output plots of _Stimela_ has its y-axis limits fixed to values from 0 to +2. Their is need to allow the user the option of changing these default values at will - if one wants to zoom-in to the plots to check for existence of some structures in the plots. It will be nice to have some optional parameter that will allow one to change these _**gain plots axis limits**_ in _Stimela_.

**Comment by SpheMakh** [comment]
being fixed [here](https://github.com/ska-sa/owlcat/issues/25)
